import commune as c

class Emoji(c.Module):
    @classmethod
    def emoji(cls,  name:str):
        emojis = []
        for k,v in cls.emojis.items():
            if name in k:
                emojis += [v]
   
        return c.choice(emojis)
        
    emojis = {'dank': '🔥',
            'error': '💥',
            'white': '🕊️',
            'cool': '😎',
            'success': '✨',
            'sad': '😢',
            'time': '🕒',
            'count': '🔢',
            'output': '📤',
            'input': '📥',
            'party': '🥳',
            'fireworks': '🎆',
            'explosion': '💣',
            'alien': '👽',
            'rocket': '🚀',
            'money': '💰',
            'victory': '✌️',
            'unicorn': '🦄',
            'rainbow': '🌈',
            'music': '🎵',
            'pizza': '🍕',
            'taco': '🌮',
            'sunglasses': '😎',
            'flame': '🔥',
            'diamond': '💎',
            'savage': '😈',
            'laughing': '😂',
            'ninja': '🥷',
            'skull': '💀',
            'thumbs_up': '👍',
            'thumbs_down': '👎',
            'crown': '👑',
            'cyber_eye': '👁️‍🗨️',
            'data_stream': '🌐', 
            'brain': '🧠',
            'robot': '🤖',
            'lightning': '⚡',
            'heart': '❤️',
            'heartbreak': '💔',
            'heartpulse': '💗',
            'green_heart': '💚',
            'blue_heart': '💙',
            'purple_heart': '💜',
            'yellow_heart': '💛',
            'orange_heart': '🧡',
            'error': '💥',
            'cross': '❌',
            'check': '✅',
            'wrong': '❌',
            'right': '✅',
            'correct': '✅',
            'incorrect': '❌',
            'checkmark': '✅',
            'check_mark': '✅',
            'checkered_flag': '🏁',
            'warning': '⚠️',
            'warning_sign': f'⚠️',
            'question': '❓',
            'happy': '😀',
            'sad': '😢',
            'angry': '😠',
            'angry_face': '😠',
            'angry_face_with_horns': '👿',
            'devil': '😈',
            'red_circle': '🔴',
            'green_circle': '🟢',
            'blue_circle': '🔵',
            'yellow_circle': '🟡',
            'orange_circle': '🟠',
            'purple_circle': '🟣',
            'black_circle': '⚫',
            'white_circle': '⚪',
            'brown_circle': '🟤',
            'red_square': '🟥',
            'green_square': '🟩',
            'blue_square': '🟦',
            'yellow_square': '🟨',
            'orange_square': '🟧',
            'purple_square': '🟪',
            'black_square': '⬛',
            'white_square': '⬜',
            'brown_square': '🟫',
            'satellite': '🛰️',
            'satellite_antenna': '📡',
            'computer': '💻',
            
    }

