alpha: 0.5
batch_size: 64
fn: null
initial_sleep: 5
max_leaderboard_age: 3600
max_staleness: 1
max_success_staleness: 100
maxsize: 128
min_leaderboard_weight: 0
mode: thread
netuid: 0
network: subspace
print_interval: 5
sample_interval: 0.1
search: null
start: true
sync_interval: 100
threads_per_worker: 64
timeout: 10
timeout_info: 4
verbose: false
debug: false
vote_interval: 100
workers: 1
