
# network
network: subspace # the network to connect to (bittensor, commune, local) to specify subnet, (subspace.0 or subspace.text)
netuid: 0 # (OPTIONAL) if you have a voting network with subnets [bittensor, commune]
sync_interval: 1000
sample_interval: 0.005 # the sleep interval between sending samples
search: null # the search for modules in the namespace
fn : null # the function to filter

# worker
mode: thread # the mode of the worker (thread, process, server)
batch_size: 64 # the batch size for the worker
workers: 1 # the number of workers

# thread executor
threads_per_worker: 64 # the number of threads
maxsize: 64 # the queue sizze

# epoch
timeout_info: 4
timeout: 10
max_staleness: 0  # the minimum interval to update the network
alpha: 0.5 # the ma average means i value no historical weight from previous moving average. 0 means you dont update anythijng fro the future ([0,1])
max_leaderboard_age: 3600 # the maximum age of the leaderboard 
max_sent_staleness: 20

# eval
min_weight_for_storage: 0 # the minimum weight before storage

# run loop
initial_sleep : 5 # the initial sleep time before running the loop
print_interval: 5 # the sleep interval between sending samples
vote_interval: 100 # the interval to vote (in blocks (8 seconds per block))

# logging
verbose: True # the verbosity of the logging
start: True # starts the event loop
debug: False # for debuging 

