# NETWORK CONFIGURATION
network: local # for local subspace:test or test # for testnet subspace:main or main # for mainnet
netuid: 0 # (NOT LOCAL) the subnetwork uid or the netuid. This is a unique identifier for the subnetwork 
subnet : null # (OPTIONAL) the subnet name which overrides the netuid if it is not null
search: null # (OPTIONAL) the search string for the network 
max_network_staleness: 60 # the maximum staleness of the network
# LOGGING CONFIGURATION
verbose: false # the verbose mode for the worker
debug : false # this is also the same as verbose (we need to change this to true)

# WORKER EPOCH CONFIGURATION
max_size: 128
threads_per_worker: 64 
mode: thread
search: null
batch_size: 64
workers: 1 # the number of workers

# MODULE EVAL CONFIGURATION
storage_path: null # the storage path for the module eval, if not null then the module eval is stored in this directory
alpha: 1.0 # 
timeout: 10 # timeout per evaluation of the module
timeout_info: 4 # (OPTIONAL) the timeout for the info worker
score_fns : ['score_module', 'score', 'reward'] # the score functions
max_staleness: 60 # the maximum staleness of the worker
max_success_staleness: 100 # the maximum staleness of the worker
result_keys : ['w', 'address', 'name', 'key', 'latency', 'staleness'] # the keys for the module eval
expected_info_keys : ['w', 'address', 'name', 'key'] # the keys for the expected info function

# LEADERBOARD CONFIGURATION
max_leaderboard_age: 3600 # the maximum age of the leaderboard befor it is refreshed
min_leaderboard_weight: 0 # the minimum weight of the leaderboard


# RUN LOOP CONFIGURATION for background loop
run_step_interval: 3 # the interval for the run loop to run
run_loop: true # This is the key that we need to change to false
vote_interval: 100 # the number of iterations to wait before voting


