# Use an official Node.js runtime as a base image
FROM node:latest

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY . .
# Install project dependencies
RUN npm install

# Copy the rest of the application code to the working directory


# Expose the port that your Next.js app will run on
EXPOSE 3000

# Command to run your Next.js app
CMD ["npm", "run dev"]
