export const SAVE_TRANSACTION_SUCCESS = 'SAVE_TRANSACTION_SUCCESS'
export const SAVE_TRANSACTION_FAILED = 'SAVE_TRANSACTION_FAILED'
export const SAVE_METAMASK_SUCCESS = 'SAVE_METAMASK_SUCCESS'
export const SAVE_METAMASK_FAILED = 'SAVE_METAMASK_FAILED'
export const LOADING = 'LOADING'
export const DONE = 'DONE'

export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const POST_USERS_REQUEST = "POST_USERS_REQUEST";
export const POST_USERS_SUCCESS = "POST_USERS_SUCCESS";
export const POST_USERS_FAILURE = "POST_USERS_FAILURE";

export const LOGIN_USERS_REQUEST = "LOGIN_USERS_REQUEST";
export const LOGIN_USERS_SUCCESS = "LOGIN_USERS_SUCCESS";
export const LOGIN_USERS_FAILURE = "LOGIN_USERS_FAILURE";

export const LOGOUT = "LOGOUT";

export const UPDATE_USERS_REQUEST = "UPDATE_USERS_REQUEST";
export const UPDATE_USERS_SUCCESS = "UPDATE_USERS_SUCCESS";
export const UPDATE_USERS_FAILURE = "UPDATE_USERS_FAILURE";

export const PUBKEY = "PUBKEY";
