###############
# conststants #
###############
DEFAULT_TARGET_GUIDANCE_SCALE = 15
DEFAULT_SOURCE_GUIDANCE_SCALE = 3.5
DEFAULT_DIFFUSION_STEPS = 50
DEFAULT_SKIP_STEPS = 25
DEFAULT_SEED = 0


DEFAULT_SEGA_CONCEPT_GUIDANCE_SCALE = 7
DEFAULT_WARMUP_STEPS = 2
DEFAULT_THRESHOLD = 0.95
DEFAULT_NEGATIVE_GUIDANCE = False

STYLE_SEGA_CONCEPT_GUIDANCE_SCALE = 7
STYLE_WARMUP_STEPS = 2
STYLE_THRESHOLD = 0.5

FACE_SEGA_CONCEPT_GUIDANCE_SCALE = 5
FACE_WARMUP_STEPS = 2
FACE_THRESHOLD = 0.95

OBJECT_SEGA_CONCEPT_GUIDANCE_SCALE = 12
OBJECT_WARMUP_STEPS = 5
OBJECT_THRESHOLD = 0.9