version: '3'

services:
  nextjs:
    build:
      context: ./nextjs-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev