version: '3.8'

services:
  api:
    build: .
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    environment:
      - HOST=${HOST:-localhost}
    restart: unless-stopped