

services:

  app:
    build:
      context: ./
    container_name: app
    # restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=3000