version: '3.8'

services:
  alice:
    build: .
    container_name: substrate-alice
    command: [
      "./target/release/node-template",
      "--chain=local",
      "--alice",
      "--node-key=0000000000000000000000000000000000000000000000000000000000000001",
      "--base-path=/tmp/alice",
      "--port=30333",
      "--ws-port=9944",
      "--rpc-port=9933",
      "--validator",
      "--rpc-methods=Unsafe",
      "--ws-external",
      "--rpc-external",
      "--rpc-cors=all"
    ]
    ports:
      - "9933:9933"
      - "9944:9944"
      - "30333:30333"
    networks:
      - substrate-testnet
    volumes:
      - alice-data:/tmp/alice

  bob:
    build: .
    container_name: substrate-bob
    command: [
      "./target/release/node-template",
      "--chain=local",
      "--bob",
      "--node-key=0000000000000000000000000000000000000000000000000000000000000002",
      "--base-path=/tmp/bob",
      "--port=30334",
      "--ws-port=9945",
      "--rpc-port=9934",
      "--validator",
      "--bootnodes=/dns/alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp",
      "--rpc-methods=Unsafe",
      "--ws-external",
      "--rpc-external",
      "--rpc-cors=all"
    ]
    ports:
      - "9934:9934"
      - "9945:9945"
      - "30334:30334"
    networks:
      - substrate-testnet
    volumes:
      - bob-data:/tmp/bob
    depends_on:
      - alice

networks:
  substrate-testnet:
    driver: bridge

volumes:
  alice-data:
  bob-data: