# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Python image from the Docker Hub
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the requirements and source code into the container
COPY pyproject.toml /app/
COPY src /app/src

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir hatchling

# Install the project in the container
RUN pip install --no-cache-dir /app

# Define environment variables
ENV POLYMARKET_API_KEY="<insert api key>"

# Run the server
CMD ["python", "src/polymarket_mcp/server.py"]