# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production

# Bundle app source
COPY . .

# Expose standard IO for MCP
# No port exposure needed for stdio

# Start the MCP server
CMD ["node", "index.js"]
